---
title: "Fitbit Flex"
author: "Howanu"
date: "Saturday, October 17, 2015"
output: html_document
---

TODO: aggregate by date, not category. Append measurement column name
to the category, e.g. Body_Weight or Activities_Steps

```{r libraries}
library(plyr)
```


```{r read_fns}
# IN: full path to a fitbit file that has sections separated by blank lines
# OUT: List of sections
read_n_split_fn <- function(fullpath) {
  raw = readLines(fullpath)
  after_blank_line_ndx <- grep ("^$",raw)+1
  ndx_ndx             <- grep("^[a-zA-Z]+", raw[after_blank_line_ndx])
  
  start_line <- c(1,after_blank_line_ndx[ndx_ndx])
  end_line <- c((start_line - 1)[-1], length(raw))

  mlply(matrix(c(start_line, end_line), ncol=2),
        function(s,e) { raw[s:e] })
}

# IN: A section from the fitbit file
# OUT: A data frame for the section
parse_section <- function(section) {
  category <- section[1]
  df <- read.csv(text=section[-1])
  df$category <- category
  df
}

# IN: A fitbit file
# OUT: A data frame for the file
parse_one_file <- function(filename) { 
  df <- ldply(read_n_split_fn(filename), parse_section)
  df$filename <- filename
  df
  }
              
# IN: A data directory
# OUT: A data frame for all fitbit files in the directory
parse_data_dir <- function(data_dir) {
  ldply(dir(path = data_dir, pattern = "*.csv", 
            full.names = TRUE,ignore.case = TRUE),
        parse_one_file)
}
```


```{r read_data, cache=TRUE}
fb <- parse_data_dir("data")
```

## Data Summary

There were `r length(unique(fb$filename))` files,
`r length(unique(fb$category))` measurement categories,
and `r nrow(fb)` measurement days.
